import Link from "next/link";

const projects = [
  { name: "Artree Nepal", type: "Brand / Web experience", year: "2026", blurb: "A bold digital home for a creative Nepal-based brand.", tone: "from-lime-300 via-emerald-300 to-cyan-300", mark: "AN", url: "https://artree-nepal.vercel.app/" },
  { name: "Plumeria", type: "E-commerce / Identity", year: "2026", blurb: "A softer, more considered shopping experience for a lifestyle brand.", tone: "from-fuchsia-300 via-rose-300 to-orange-200", mark: "PL", url: "https://plumeria-theta.vercel.app/" },
  { name: "GharBazaar", type: "Property platform", year: "2026", blurb: "Making the search for a place to call home feel a little easier.", tone: "from-sky-300 via-indigo-300 to-violet-300", mark: "GB", url: "https://gharbazaar-red.vercel.app/" },
  { name: "NepKicks", type: "Retail / Commerce", year: "2025", blurb: "A high-energy storefront built for browsing, choosing, and buying.", tone: "from-amber-200 via-orange-300 to-red-300", mark: "NK", url: "https://nepkicks.vercel.app/" },
  { name: "Pokhara Pizza", type: "Food / Local business", year: "2025", blurb: "A warm, local-first web presence for a Pokhara favourite.", tone: "from-yellow-200 via-lime-300 to-green-300", mark: "PP", url: "https://pokhara-pizza-dw9l.vercel.app/" },
];

export default function ProjectsPage() {
  return <main><header className="site-header"><Link href="/" className="brand"><img src="/logo1.png" alt="Krishna Rawal logo" width="36" height="44" /><span>krishna<span className="muted">.rawal</span></span></Link><nav className="desktop-nav"><Link href="/#about">about</Link><Link href="/projects" className="active-link">projects</Link><Link href="/#notes">notes</Link><Link href="/#contact" className="nav-cta">let&apos;s talk ↗</Link></nav><details className="mobile-menu"><summary>menu</summary><div><Link href="/">home</Link><Link href="/#about">about</Link><Link href="/#contact">let&apos;s talk ↗</Link></div></details></header><section className="projects-hero shell"><p className="eyebrow"><span className="status-dot" /> selected work / 2025—26</p><h1>Things I&apos;ve<br /><span>made recently.</span></h1><p>Some experiments, collaborations, and client work where design, technology, and a little bit of obsession came together.</p></section><section className="project-list shell">{projects.map((project, index) => <article className="project-line" key={project.name}><div className={`project-art bg-gradient-to-br ${project.tone}`}><span className="project-mark">{project.mark}</span><span className="project-caption">0{index + 1} / case study ↗</span></div><div className="project-line-copy"><div className="project-line-top"><span className="eyebrow">{project.type}</span><span className="project-year">{project.year}</span></div><h2>{project.name}</h2><p>{project.blurb}</p><a className="text-link" href={project.url} target="_blank" rel="noreferrer">view project <span>↗</span></a></div></article>)}</section><footer className="site-footer shell"><span>© 2026 Krishna Rawal</span><span>built with curiosity <b>✳</b></span><Link href="/">back home ↗</Link></footer></main>;
}
