import Link from "next/link";

const projects = [
  { name: "Artree Nepal", type: "Brand / web experience", year: "2026", mark: "AN", tone: "mint", blurb: "A bold digital home for a creative Nepal-based brand.", url: "https://artree-nepal.vercel.app/" },
  { name: "GharBazaar", type: "Property platform", year: "2026", mark: "GB", tone: "blue", blurb: "Making the search for a place to call home feel a little easier.", url: "https://gharbazaar-red.vercel.app/" },
  { name: "Plumeria", type: "E-commerce / identity", year: "2026", mark: "PL", tone: "rose", blurb: "A softer, more considered shopping experience for a lifestyle brand.", url: "https://plumeria-theta.vercel.app/" },
  { name: "NepKicks", type: "Retail / commerce", year: "2025", mark: "NK", tone: "orange", blurb: "A high-energy storefront built for browsing, choosing, and buying.", url: "https://nepkicks.vercel.app/" },
  { name: "Pokhara Pizza", type: "Food / local business", year: "2025", mark: "PP", tone: "yellow", blurb: "A warm, local-first web presence for a Pokhara favourite.", url: "https://pokhara-pizza-dw9l.vercel.app/" },
];

export default function ProjectsPage() {
  return <main><header className="site-header shell"><Link href="/" className="logo-link" aria-label="Krishna Rawal home"><span className="logo-glow" /><img src="/logo1.png" alt="Krishna Rawal" /></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/#about">about</Link><Link href="/projects" className="active">work</Link><Link href="/#graphics">graphics</Link><Link href="/#contact" className="nav-button">let&apos;s talk <span>↗</span></Link></nav><details className="mobile-menu"><summary>menu</summary><div><Link href="/">home</Link><Link href="/#about">about</Link><Link href="/#contact">let&apos;s talk ↗</Link></div></details></header><section className="projects-intro shell"><p className="eyebrow-line"><span className="live-dot" /> selected work / 2025—26</p><h1>Built with intent.<br /><span>Shipped with care.</span></h1><p>Websites and digital experiences where the brief was simple: make it clear, make it useful, make it feel like the people behind it.</p></section><section className="projects-table shell">{projects.map((project, index) => <article className="project-item" key={project.name}><div className={`project-tile ${project.tone}`}><span>{project.mark}</span><small>0{index + 1}</small></div><div className="project-details"><div className="project-meta"><span>{project.type}</span><span>{project.year}</span></div><h2>{project.name}</h2><p>{project.blurb}</p><a className="under-link" href={project.url} target="_blank" rel="noreferrer">view live project <span>↗</span></a></div></article>)}</section><footer className="site-footer shell"><span>© 2026 Krishna Rawal</span><span>built in Nepal with curiosity</span><Link href="/">back home ↗</Link></footer></main>;
}
